### PR TITLE
Fix kafka server name per the new specification

### PR DESCRIPTION
**Pull request by AparnaKarve**
The Kafka deployment has undergone some changes and the new name for the server needs to be -

`platform-mq-dev-kafka-brokers.platform-mq-dev.svc`

This resolves the DNS lookup error that I was seeing earlier and starts the `aiops-incoming-listener` pod successfully.

### CODE REVIEW

**Review by tumido — CHANGES_REQUESTED** [review]
This PR is not needed. Obviously every setup would need some values changed. That's why it's called an environment variable. The default value for `KAFKA_SERVER` suits the needs of production deployment. If you want a different value you can always modify that in OpenShift for your specific setup.

**Comment by tumido** [comment]
This PR is not needed as is. However if you rewrite it, so the `KAFKA_SERVER` is a template parameter with a default value of the current env variable, that might be a good strategy.

**Comment by AparnaKarve** [comment]
> If you want a different value you can always modify that in OpenShift for your specific setup.

True -- although I think it will be a good idea to start off with the right value (will be helpful for folks who are just onboarding)

I will also explore the template parameter option.
Thanks.

**Comment by tumido** [comment]
The `platform-mq-dev-kafka-brokers.platform-mq-dev.svc` is definitely not the right value here. It's a hostname that only "works" in insights-dev cluster and only if the dev instance of kafka is deployed. Our templates should not default to any other dev stage service, never. The template should describe a definite, stable setup. Based on IPPs and negotiated APIs. Therefore we should always point to the stable production-grade service.

If you make this configurable, with the production message bus hostname as the default, that's acceptable. Not a necessary change, but acceptable.

The `platform-mq-cluster-kafka.platform-mq.svc:9092` (or whatever the prod host name would be) is a stable resource. Or at least it should be. Platform-wise.

What would we do if they remove the dev instance? Change the template again? And what would you do when we deploy to the insights cluster instead of insights-dev?

**Comment by tumido** [comment]
Closing in favor of #8

**Pull request closed without merging**
