### PR TITLE
Outlier detection

### PR DESCRIPTION
**Pull request by jameswnl**
@tumido @AparnaKarve can you help review this?

### CODE REVIEW

**Review by tumido — COMMENTED** [review]
I like it! Looks clean and nice to me! Maybe we should lock the `rad` lib to a version, as a release? And then lock it? :wink: This way it's locked to a commit, so it gets updated to master of the `rad` by each `pipenv lock`. Should I push a release into the rad repo? :)

**Comment by AparnaKarve** [comment]
@jameswnl Is the per-host info part not implemented in this iteration?

FYI, the output JSON in the other use case contains a dict with the `hosts` key that has per-host info. This per-host info is used by aiops-consumer to publish messages for Advisor.

**Comment by AparnaKarve** [comment]
@jameswnl In the per-host info dict, we also output Cluster name

The Topological Inv. API gives us the Cluster info, like the Cluster name.

I know this use case is only using the Host Inv. API and not the Topology Inv. API, so getting the Cluster name might be an additional step (and would involve talking to the Topological Inv. API )

Probably a good time to check with Jerome, if we can skip displaying the Cluster name in the Advisor UI for this use case

**Comment by jameswnl** [comment]
@AparnaKarve This initial iteration is kind of the `training` step. It is creating the `isolation_forest` which can be used for predicting an unknown hosts later on.

The creation of the `isolation_forest` will also have the effects of publishing a scores table that lists the anomalous scores of each systems in that account.

Regarding the Custer name, this use case is an unsupervised model and it doesn't care if a host is in a cluster or not.  If a host is in a cluster and its cluster nature gives it some very features that is very different from the other hosts, then this host will likely to be detected (and we really hope we do) as anomaly.  However, if a cluster really has no extra-ordinary features, (e.g. most of this account's hosts are in a same cluster) it won't be flagged.

**Review by parsahosseini — COMMENTED** [review]
good work.
a recent bug-fix grew `rad==0.8.2` to `rad==0.8.3`... but other than that, good stuff.

**Comment by jameswnl** [comment]
@parsahosseini the fix is not merged yet. we can have another PR to update the pinning version.
I'm trying to get this batch work in so that we have an end-to-end feature .

**Comment by parsahosseini** [comment]
@jameswnl correct... when reviewers / assignees have time, they can approve the changes and have 0.8.3 be the good-to-go version

**Review by AparnaKarve — APPROVED** [review]
@jameswnl LGTM for the first round!

We will need the `hosts` dict that I mentioned about earlier.

Hosts that have anomalies should have a `recommendations` array that provide the anomaly details.
Hosts that do not have anomalies should have an empty `recommendations` array.
A follow-up PR for this task would be great!

**Pull request merged**
